# Copyright (C) 2020 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#
include $(TOPDIR)/rules.mk
LUCI_TITLE:=LuCI support for serverchan with DING Talk
LUCI_DEPENDS:=+iputils-arping +curl
LUCI_PKGARCH:=all
PKG_VERSION:=2.00
PKG_RELEASE:=6

include $(TOPDIR)/feeds/luci/luci.mk
# call BuildPackage - OpenWrt buildroot signature